defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Kwak Woo Young
subtitle: I want to be Developer

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Kwak Woo Young"

# Side Menu Links
menu:
  - text: My ProFile
    link: /
    icon: ""

  - text: Skills
    link: /skills-and-offers
    icon: ""

  - text: Education
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

  - text: PortFolio
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
 

  - name: github
    link: https://github.com/rhkrdndud22
    icon: fab fa-github-square

  
 

    
